name: CI Pipeline Pull

on:
  push:
  # Habilitar o gatilho manual atravs da interface do Github Actions
  workflow_dispatch:

jobs:
  # Job para execução dos tests
  tests:
    name: Tests runner
    runs-on: ubuntu-latest
    #Configuração de passos do nosso job
    steps:
      # 1. Chck-out do código fonte
      - uses: actions/checkout@v3
      # 2. Configurar a JDK na máquina
      - name: Set up JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      # 3. Executar os testes da aplicação
      - name: Run application tests
        run: ./gradlew test
